<?php

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\file\FileInterface;
use Drupal\iq_group\Controller\UserController;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupContent;
use Drupal\iq_group\MauticEvents;
use Drupal\iq_group\Event\MauticEvent;
use Drupal\node\NodeInterface;
use Drupal\user\UserInterface;
use Drupal\views\ViewExecutable;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function iq_group_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['account']['name']['#type'] = 'hidden';
  $form['account']['name']['#required'] = FALSE;
  $form['actions']['submit']['#submit'][] = 'iq_group_after_register';
  $form['#validate'][] = 'iq_group_register_validation';
  $form['#validate'] = array_reverse($form['#validate']);
  //var_dump($form['#validate']);
  //var_dump(array_keys($form['account']));
  //die();
}

function iq_group_form_node_iq_group_whitepaper_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /*var_dump($form['field_iq_group_whitepaper_file']['widget']);
  die();*/
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function iq_group_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['language']['#type'] = 'markup';
  $form['account']['name']['#type'] = 'hidden';
  $form['account']['mail']['#description'] = '';
  //$form['actions']['submit']['#submit'][] = 'iq_group_after_register';
  foreach ($form['field_iq_group_preferences']['widget']['#options'] as $key => $value) {
    if (reset($value) == 'General') {
      unset($form['field_iq_group_preferences']['widget']['#options'][$key]);
    }
  }

}

function iq_group_register_validation(&$form, FormStateInterface $form_state) {
  $form_state->setValue('name', $form_state->getValue('mail'));
  $form['account']['name']['#value'] = $form_state->getValue('mail');
}

/**
 * Additional submit function after user register.
 */
function iq_group_after_register(&$form, FormStateInterface $form_state, $form_id) {
  // email exists
  $mail = $form_state->getValue('mail');
  @$user = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties([
    'mail' => $mail
  ]);
  /** @var \Drupal\user\Entity\User $user */
  $user = reset($user);

  if ($user != FALSE) {
    $iqGroupSettingsConfig = \Drupal::config('iq_group.settings');
    $email_name = $iqGroupSettingsConfig->get('name') != NULL ? $iqGroupSettingsConfig->get('name') : 'Iqual';
    $email_from = $iqGroupSettingsConfig->get('from') != NULL ? $iqGroupSettingsConfig->get('from') : 'support@iqual.ch';
    $email_reply_to = $iqGroupSettingsConfig->get('reply_to') != NULL ? $iqGroupSettingsConfig->get('reply_to') : 'support@iqual.ch';
    if ($form_state->getValue('pass') != NULL) {
      if ($user->field_iq_group_user_token->value == NULL) {
        $data = time();
        $data .= $user->id();
        $data .= $user->getEmail();
        $hash_token =  Crypt::hmacBase64($data, Settings::getHashSalt() . $user->getPassword());
        $user->set('field_iq_group_user_token', $hash_token);
      }
      // Add the role in general (id=5) group.
      $group = Group::load(\Drupal::config('iq_group.settings')->get('general_group_id'));
      $group_role_storage = \Drupal::entityTypeManager()->getStorage('group_role');
      $groupRoles = $group_role_storage->loadByUserAndGroup($user, $group);
      $groupRoles = array_keys($groupRoles);
      if (!in_array('subscription-lead', $groupRoles)) {
        UserController::addGroupRoleToUser($group, $user, 'subscription-lead');
        $eventDispatcher = \Drupal::service('event_dispatcher');
        $eventDispatcher->dispatch(MauticEvents::USER_PROFILE_EDIT, new MauticEvent($user));
      }
      // Add member to the other groups that the user has selected in the
      // preferences field.
      $groups = $form_state->getValue('preferences');
      if ($groups != NULL && !empty($groups)) {
        foreach ($groups as $key => $otherGroup) {
          $otherGroup = Group::load($otherGroup);
          if ($otherGroup != NULL)
            UserController::addGroupRoleToUser($otherGroup, $user, 'subscription-lead');
        }
      }
    }
    \Drupal::messenger()->deleteByType(\Drupal\Core\Messenger\MessengerInterface::TYPE_STATUS);
    \Drupal::messenger()->addMessage('Besten Dank für die Registrierung. Sie erhalten in Kürze von uns eine E-Mail mit einem Bestätigungslink.');
    if ($form_state->getValue('destination') != "")  {
      $destination = $form_state->getValue('destination');
    }
    else {
      // @todo Set a destination if it is a signup form or not?
      //$destination = \Drupal\Core\Url::fromRoute('<current>')->toString();
    }
    $url = 'https://' . \Drupal\iq_group\Form\SignupForm::getDomain() . '/auth/' . $user->id() . '/' . $user->field_iq_group_user_token->value;
    if (isset($destination) && $destination != NULL) {
      $url .= "?destination=" . $destination;
    }
    $renderable = [
      '#theme' => 'register_template',
      '#EMAIL_TITLE' => 'Registrierung Benutzerkonto SQS',
      '#EMAIL_PREVIEW_TEXT' => 'Registrierung Benutzerkonto SQS',
      '#EMAIL_URL' => $url,
    ];
    $rendered = \Drupal::service('renderer')->renderPlain($renderable);
    $mail_subject = t("Registrierung Benutzerkonto SQS");
    mb_internal_encoding("UTF-8");
    $mail_subject  = mb_encode_mimeheader($mail_subject,'UTF-8','Q');
    // Send a registration email and set the pending activation flag.
    $result = mail($user->getEmail(), $mail_subject , $rendered,
      "From: ".$email_name ."<". $email_from ."> ". "\r\nReply-to: ". $email_reply_to . "\r\nContent-Type: text/html");
    $store = \Drupal::service('user.shared_tempstore')->get('iq_group.user_status');
    $store->set($user->id().'_pending_activation', true);
    $form_state->setRedirect('user.register');

  }


}

/**
 * Implements hook_user_login().
 */
function iq_group_user_login(\Drupal\user\UserInterface $account) {


  $group = Group::load(\Drupal::config('iq_group.settings')->get('general_group_id'));
  $group_role_storage = \Drupal::entityTypeManager()->getStorage('group_role');
  $groupRoles = $group_role_storage->loadByUserAndGroup($account, $group);
  $groupRoles = array_keys($groupRoles);
  if (in_array('subscription-lead', $groupRoles)) {
    // redirect to destination if there is 1
    if (isset($_GET['destination']) && $_GET['destination'] != NULL) {
      $destination = $_GET['destination'];
      header("Location:".$destination);
    }
    // if not, he will be redirect to the set default redirect from
    // iq group settings.
    else {
      $member_area = \Drupal::config('iq_group.settings')->get('default_redirection');
      $response = new RedirectResponse(Url::fromUserInput($member_area)->toString());
      $response->send();
    }
  }
  return ;

  if (in_array('subscription-subscriber', $groupRoles)) {
    // redirect to destination if there is 1
    if (isset($_GET['destination']) && $_GET['destination'] != NULL) {
      $destination = $_GET['destination'];
      header("Location:".$destination);
    }
    // if not, he will be redirect to the set default redirect from
    // iq group settings.
    else {
      header('Location:' . \Drupal::config('iq_group.settings')->get('default_redirection'));
    }
  }

}

/**
 * Implements hook_file_access().
 */
function iq_group_file_access(FileInterface $file, $operation, AccountInterface $account) {
  // Block access to private file uploads for anonymous users.
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  if (\Drupal::currentUser()->isAnonymous()) {
    return AccessResult::forbidden();
  }
  else {
    $group = Group::load(\Drupal::config('iq_group.settings')->get('general_group_id'));
    $group_role_storage = \Drupal::entityTypeManager()->getStorage('group_role');
    $groupRoles = $group_role_storage->loadByUserAndGroup($user, $group);
    $groupRoles = array_keys($groupRoles);
    if (in_array('subscription-lead', $groupRoles) || in_array('subscription-subscriber', $groupRoles)) {
      return AccessResult::allowed();
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_file_download().
 */
function iq_group_file_download($uri) {
  /** @var \Drupal\file\Entity\File $file */
  $file = \Drupal::entityTypeManager()->getStorage('file')->loadByProperties(['uri' => $uri]);
  $file = reset($file);
  if ($file != NULL) {
    $whitepaper = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
      'type' => 'iq_group_whitepaper',
      'field_iq_group_whitepaper_file' => $file->id(),
    ]);
    $whitepaper = reset($whitepaper);
    if (isset($whitepaper) && $whitepaper->id() > 0)
    {
      $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
      $existing_downloads = $user->get('field_iq_group_downloads')
        ->getValue();
      $downloads = [];
      if (!empty($existing_downloads)) {
        foreach ($existing_downloads as $key => $val) {
          if ($val['target_id'] != $whitepaper->id())
            $downloads[] = $val['target_id'];
        }
      }
      $downloads[] = $whitepaper->id();
      $user->set('field_iq_group_downloads', $downloads);
      $user->save();
      $eventDispatcher = \Drupal::service('event_dispatcher');
      $eventDispatcher->dispatch(MauticEvents::USER_DOWNLOAD_WHITEPAPER, new MauticEvent($user));
    }
  }
}

/**
 * Feature to create the group content on a node create/edit.
 */
/**
 * Get content types and field to act.
 */
function _node_field_group_settings() {
  $ctypes = [
    'iq_group_whitepaper',
  ];
  $add = $edit = array();
  foreach ($ctypes as $ctype) {
    $add[] = 'node_' . $ctype . '_form';
    $edit[] = 'node_' . $ctype . '_edit_form';
  }
  return [
    'form_id_add' => $add,
    'form_id_edit' => $edit,
    'group_field' => 'field_iq_group_node_group',
  ];
}


function iq_group_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'iq_group_user_edit_form') {

  }
  if ($form_id == 'user_register_form') {
    $form['user_picture']['widget'][0]['#description'] = 'Erlaubte dateitypen: ' . reset($form['user_picture']['widget'][0]['#upload_validators']['file_validate_extensions']);
    $form['data_privacy'] = [
      '#type' => 'checkbox',
      '#title' => t('I have read the terms and conditions and data protection regulations and I agree.'),
      '#default_value' => false,
      '#required' => true,
      '#weight' => 10,
    ];
    $form['actions']['#submit'][] = '_node_field_group_add_custom_callback_group';
/*    $result = \Drupal::entityTypeManager()
      ->getStorage('group')
      ->loadMultiple();
    $options = [];
    foreach ($result as $key => $group) {
      $options[$group->id()] = $group->label();
    }
    $form['field_iq_group_preferences']['widget']['#options'] = $options;*/
  }
  $settings = _node_field_group_settings();
  // Add node.
  if (in_array($form_id, $settings['form_id_add'])) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_node_field_group_add_custom_callback_group';
      }
    }
  }

  // you need for the edit form a different callback because maybe you have to delete or create GroupContent
  if (in_array($form_id, $settings['form_id_edit'])) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_node_field_group_edit_custom_callback_group';
      }
    }
  }
}


function _node_field_group_add_custom_callback_group($form, FormStateInterface $form_state) {
  $settings = _node_field_group_settings();
  $nid = $form_state->getValue('nid');
  $node = Node::load($nid);
  $gids = $form_state->getValue($settings['group_field']);

  foreach ($gids as $gid) {
    // Skip -none- option
    if ($gid['target_id'] == '_none') {
      continue;
    }
    $group = Group::load($gid['target_id']);
    if ($group != NULL) {
      /** @var \Drupal\group\Plugin\GroupContentEnablerInterface $plugin */
      $plugin = $group->getGroupType()->getContentPlugin('group_node:'.$node->bundle());
      $group_content = GroupContent::create([
        'type' => $plugin->getContentTypeConfigId(),
        'gid' => $group->id(),
        'entity_id' => $node->id(),
      ]);
      $group_content->save();
    }
  }

}

// This function is a bit more complex because you have to do some mathematical set operations
function _node_field_group_edit_custom_callback_group($form, FormStateInterface $form_state) {
  $settings = _node_field_group_settings();
  $nid = $form_state->getValue('nid');
  $node = Node::load($nid);

  // Index-Array for wanted groups ( gid => gid )
  $gids = $form_state->getValue($settings['group_field']);
  $gids_wanted = [];
  foreach ($gids as $gid) {
    $gids_wanted[$gid['target_id']] = $gid['target_id'];
  }

  // Index-Array for existing groups for this node gid => gid
  $gids_existing = [];

  // Index-Array for gnodes for easier deletion gid => GroupContent
  $gnodes_existing = [];

  /** @var \Drupal\group\Entity\Storage\GroupContentStorageInterface $storage */
  $storage = \Drupal::entityTypeManager()->getStorage('group_content');
  // Loads all groups with a relation to the node
  $activGroupListEntity = $storage->loadByEntity($node);
  foreach ($activGroupListEntity as $groupContent) {
    // fill Index-Array with existing groups gid => gid
    $gids_existing[$groupContent->getGroup()->id()] = $groupContent->getGroup()->id();

    // fill Index-Array for existing gnodes
    $gnodes_existing[$groupContent->getGroup()->id()] = $groupContent;
  }

  // Union for existing and wanted groups
  $gids_union = $gids_existing + $gids_wanted;

  // Index-Array gnodes to create
  // = (Union for existing and wanted) minus existing
  $gids_create = array_diff($gids_union, $gids_existing);

  // Index-Array gnodes to delete
  // = (Union for existing and wanted) minus wanted
  $gids_delete = array_diff($gids_union, $gids_wanted);

  foreach ($gids_create as $gid) {
    // Skip -none- option
    if ($gid == '_none') {
      continue;
    }
    $group = Group::load($gid);
    if ($group != NULL) {
      /** @var \Drupal\group\Plugin\GroupContentEnablerInterface $plugin */
      $plugin = $group->getGroupType()->getContentPlugin('group_node:'.$node->bundle());
      $group_content = GroupContent::create([
        'type' => $plugin->getContentTypeConfigId(),
        'gid' => $group->id(),
        'entity_id' => $node->id(),
      ]);
      $group_content->save();
    }
  }

  foreach ($gids_delete as $gid) {
    // Skip -none- option
    if ($gid == '_none') {
      continue;
    }
    $gnodes_existing[$gid]->delete();
  }

}

/**
 * Implements hook_views_pre_render().
 */
function iq_group_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'whitepaper_block') {
    $registerForm = \Drupal::formBuilder()->getForm('Drupal\iq_group\Form\RegisterForm');
    // If there is a resource selected (currently whitepaper, later it may vary).
    if (\Drupal::currentUser()->isAnonymous()) {
      if ($view->filter['nid']->value['value'] != NULL) {
        unset($registerForm['preferences']);
        $registerForm['destination']['#value'] = '/node/' .reset($view->filter['nid']->value['value']);
        $destination = '/node/' .reset($view->filter['nid']->value['value']);
      }

      if (!isset($destination)) {
        $destination = \Drupal::service('path.current')->getPath();
      }
      $registerForm['register_link'] = [
        '#type' => 'markup',
        '#markup' => '<a href="/user/register?destination=' . $destination . '">' . t('Register') . '</a> / ',
        '#weight' => 100
      ];
      $registerForm['login_link'] = [
        '#type' => 'markup',
        '#markup' => '<a href="/user/login?destination=' . $destination . '">' . t('Login') . '</a>',
        '#weight' => 100
      ];
      $view->attachment_after = $registerForm;
    }
  }
}

function iq_group_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['title'] = [
    '#type' => 'markup',
    '#markup' => "<h1>Anmeldung zur SQS  Member Area</h1>",
    '#weight' => -100
  ];
  $destination = '/user/register';
  if (!empty($_GET['destination'])) {
    $destination.='?destination=' . $_GET['destination'];
  }
  $form['forgot_password'] = [
    '#type' => 'markup',
    '#markup' => '<a href="/onetime-loginlink">'. t('Forgot password') . '</a> / ',
    '#weight' => 100
  ];
  $form['register_link'] = [
    '#type' => 'markup',
    '#markup' => '<a href="'. $destination .  '">' . t('Register') . '</a>',
    '#weight' => 100
  ];
}

/**
 * Implements hook_node_access().
 *
 */
function iq_group_node_access(NodeInterface $node, $op, AccountInterface $account) {
  // We do not care about create access as we have our own wizard for that. Any
  // operation aside from 'view', 'update' and 'delete' is also unsupported.
  if (!in_array($op, ['view', 'update', 'delete'])) {
    return AccessResult::neutral();
  }

  // Some modules, including the code in \Drupal\node\NodeForm::access() may
  // check for 'view', 'update' or 'delete' access on new nodes, even though
  // that makes little sense. We need to account for it to avoid crashes because
  // we would otherwise query the DB with a non-existent node ID.
  if ($node->isNew()) {
    return AccessResult::neutral();
  }

  $plugin_id = 'group_node:' . $node->bundle();

  // Load all of the group content for this node.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByEntity($node);

  // If the node does not belong to any group, we have nothing to say.
  if (empty($group_contents)) {
    return AccessResult::neutral();
  }

  /** @var \Drupal\group\Entity\GroupInterface[] $groups */
  $groups = [];
  foreach ($group_contents as $group_content) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group = $group_content->getGroup();
    $groups[$group->id()] = $group;
  }
  if ($op == 'view') {
    foreach ($groups as $group) {
      if ($node->isPublished()) {
        if ($group->hasPermission("view $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
      }
      elseif ($group->hasPermission("view unpublished $plugin_id entity", $account)) {
        \Drupal::logger('gnode')->notice('yoo what');
        return AccessResult::allowed();
      }
      \Drupal::logger('gnode')->notice('allowed in group');
    }
    return AccessResult::forbidden();
  }
  return AccessResult::neutral();
}

function iq_group_theme($existing, $type, $theme, $path) {
  $text = '';
  return [
    'signup_template' => [
      'variables' => [
        'EMAIL_TITLE' => "Sign up",
        'EMAIL_PREVIEW_TEXT' => 'Newsletter Sign up',
        'EMAIL_URL' => $text
      ],
    ],
    'login_template' => [
      'variables' => [
        'EMAIL_TITLE' => "Login",
        'EMAIL_PREVIEW_TEXT' => 'Login',
        'EMAIL_URL' => $text
      ],
    ],
    'whitepaper_template' => [
      'variables' => [
        'EMAIL_TITLE' => "Whitepaper",
        'EMAIL_PREVIEW_TEXT' => 'Whitepaper download',
        'EMAIL_URL' => $text
      ],
    ],
    'register_template' => [
      'variables' => [
        'EMAIL_TITLE' => "Registration",
        'EMAIL_PREVIEW_TEXT' => 'Registration',
        'EMAIL_URL' => $text
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function iq_group_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {

  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  if ($entity->bundle() == 'iq_group_whitepaper') {
    $user_edit = \Drupal::formBuilder()->getForm('Drupal\iq_group\Form\UserEditForm');
    $build['user_wrapper'] = [
      '#type' => 'fieldset',
      '#title' => t('User settings'),
      '#prefix' => '<br/><br/>',
    ];
    $build['user_wrapper']['user_block'] = $user_edit;
    $build['user_wrapper']['#weight'] = 150000;
  }


}

function iq_group_form_views_exposed_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

  // Set default values for the branches from the logged in user.
  if ($form['#id'] == 'views-exposed-form-whitepapers-by-branch-page-1') {
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $ids = $user->get('field_iq_group_branches')->getValue();

    $branches = [];

    foreach ($ids as $key => $branch) {
      $branches[] = $branch['target_id'];
    }
    if (in_array(\Drupal::request()->server->get('REQUEST_METHOD'), ['GET', 'HEAD'])) {
      $form['field_iq_group_branches_target_id']['#default_value']['value'] = $branches;
      $form['field_iq_group_branches_target_id']['#value'] = $branches;
    }

  }
}


/**
 * Implements hook_ENTITY_TYPE_update().
 */
function iq_group_user_update(\Drupal\user\UserInterface $account) {
  $user = \Drupal\user\Entity\User::load($account->id());

  $group = Group::load(\Drupal::config('iq_group.settings')->get('general_group_id'));

  if ($group->getMember($user) && !$user->isNew()) {
      \Drupal::logger('iq_group')->notice('custom_user_update');

      $eventDispatcher = \Drupal::service('event_dispatcher');
      $eventDispatcher->dispatch(MauticEvents::USER_PROFILE_UPDATE, new MauticEvent($user));
  }
}