# Schema for the configuration files of the captcha module.
#wrong_response_counter

iq_group.settings:
  type: config_object
  label: 'iQual Group settings'
  mapping:
    default_redirection:
      type: string
      label: 'The default redirection for subscribers.'
    general_group_id:
      type: string
      label: 'The id of the general group for access of the content.'
    name:
      type: string
      label: 'The name of the sender in the emails.'
    from:
      type: string
      label: 'The sender email address.'
    reply_to:
      type: string
      label: 'The reply-to email address.'
    terms_and_conditions:
      type: string
      label: 'The terms and conditions link.'