# Schema for the configuration files of the captcha module.
#wrong_response_counter

iq_group.settings:
  type: config_object
  label: 'iQual Group settings'
  mapping:
    default_redirection:
      type: string
      label: 'The default redirection for subscribers.'
    redirection_after_register:
      type: string
      label: 'The redirection after register.'
    redirection_after_signup:
      type: string
      label: 'The redirection after signup.'
    redirection_after_account_delete:
      type: string
      label: 'The redirection after the account is deleted.'
    general_group_id:
      type: string
      label: 'The id of the general group for access of the content.'
    name:
      type: string
      label: 'The name of the sender in the emails.'
    from:
      type: string
      label: 'The sender email address.'
    reply_to:
      type: string
      label: 'The reply-to email address.'
    login_intro:
      type: string
      label: 'Login introduction text.'
    project name:
      type: string
      label: 'The name of the project.'
    terms_and_conditions:
      type: string
      label: 'The terms and conditions link.'
    project_address:
      type: string
      label: 'The address of the project.'
    hidden_fields:
      type: string
      label: 'The hidden fields for the import.'
