<?php

namespace Drupal\iq_group_sqs_mautic\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Provides a 'Register' Block.
 *
 * @Block(
 *   id = "register_block",
 *   admin_label = @Translation("Register block"),
 *   category = @Translation("Forms"),
 * )
 */
class RegisterBlock extends BlockBase {

  /**
   * {@inheritdoc}
   */
  public function build() {
    return \Drupal::formBuilder()->getForm('Drupal\iq_group_sqs_mautic\Form\RegisterForm');
  }

  public function blockForm($form, FormStateInterface $form_state) {
    $form = parent::blockForm($form, $form_state); // TODO: Change the autogenerated stub
    $form['media_link']  = [
      '#type' => 'entity_autocomplete',
      '#title' => 'Media',
      '#target_type' => 'node',
      '#selection_settings' => ['target_bundles' =>[ 'media' => 'media']],
      '#validate_reference' => FALSE,
      '#maxlength' => 1024,
    ];
    return $form;
  }

  public function blockSubmit($form, FormStateInterface $form_state) {
    parent::blockSubmit($form, $form_state); // TODO: Change the autogenerated stub
    $this->configuration['media_link'] = $form_state->getValue('media_link');

  }
}